### ISSUE TITLE
https://fiware.github.io/dataModels/common-schema.json is not up-to-date

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#107]
in git repository there is this additional property

"EntityIdentifierType": {
      "type": "string",
      "minLength": 1,
      "maxLength": 256,
      "pattern": "^[\\w\\-\\.\\{\\}\\$\\+\\*\\[\\]`|~^@!,:\\\\]+$"
    },

**Comment by jmcanterafonseca** [comment]
fixed.
