### ISSUE TITLE
About AirQualityThreshold

### ISSUE THREAD

**Issue by kzangeli** [Fiware/dataModels#108]
The way I understood AirQualityThreshold when reading the documentation was something like a vector of:
```
[
  {
    "from": 0,
    "to": 10,
    "quality": "bad"
  },
  {
    "from": 11,
    "to": 31,
    "quality": "acceptable"
  },
  ...
]
```
I got surprised later not finding a vector but just an object ...
Might be I simply did not understand this.

**Comment by jmcanterafonseca** [comment]
closing issue as we are no longer capturing air quality thresholds
