### ISSUE TITLE
Unclear difference between name and modelName in Waste Container Model

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#113]
The spec states:

- ```name```. Name given to the container model
Normative References: https://schema.org/name
Mandatory

- ```modelName```. Name of the model.
Attribute type: Text
See also: https://schema.org/model
Optional

Also, ```name``` is mandatory in the specification, but it's missing in the example json in the documentation, while ```modelName``` is present.

**Comment by jmcanterafonseca** [comment]
`name` is an attribute that applies to any physical object. It allows to give a "well-known" or code name to a physical object. It would allow municipalities to quickly find container models in the database. ' A code name can be Mnemotechnical such as 'green_bin_trolley_year_209' 

A different thing is the modelName, that together with the brandName define the specific container model from a formal point of view i.e. what brand and what specific model, which could be something like 'WasteAssociates' model 'A4567' . 

We need to fix the example

**Comment by jmcanterafonseca** [comment]
fixed as per the comment above and with #182 landed
