### ISSUE TITLE
align data models with comments coming from smart santander

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#126]

**Comment by cclauss** [comment]
What comments?

**Comment by jmcanterafonseca** [comment]
they are in Spanish unfortunately

**Comment by aarranz** [comment]
Anyway, It would be great to make those comments public so people understanding Spanish can help 😉.

**Comment by jmcanterafonseca** [comment]
if SmartSantander has comments, they should be reported here as issues
