### ISSUE TITLE
refactor point of interaction and fix file location

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/dataModels#127]

**Comment by jmcanterafonseca** [comment]
@FRDavid please could you work to fix this issue?

**Comment by FRDavid** [comment]
I'm sorry @jmcanterafonseca, I missed the first message and I'm out of context,

What should I do to complete the task? Could you specify more?

It's about create the [harmonised definition](https://github.com/GSMADeveloper/HarmonisedEntityDefinitions/blob/master/PointOfInterest.md)?

It's about file organization?
- doc/spec.md
- example.json
- schema.json

Best regards and sorry for the inconvenience

**Comment by jmcanterafonseca** [comment]
yes  you need to have the same file organization as other data models. That includes creating a schema.json and example.json consistent with the specification of the data model.

**Comment by FRDavid** [comment]
Ok in file organization. What do you mean with refactor?

**Comment by jmcanterafonseca** [comment]
for the time being nothing ... but I don't recall

2017-10-03 13:10 GMT+02:00 David <notifications@github.com>:

**Comment by jmcanterafonseca** [comment]
fixed
