### ISSUE TITLE
Question regarding optional metadata on some attributes

### ISSUE THREAD

**Issue by PedroMD** [Fiware/dataModels#139]
Hello all,

I would like to have some clarification regarding the `metadata` attribute of other **mandatory** attributes whose type is not `StructuredValue`. 

As an example, please take a look at the StreetLighting model:
https://github.com/Fiware/dataModels/blob/master/StreetLighting/Streetlight/doc/spec.md

+ `status` : The overall status of this street light. 
    + Attribute type: [Text](http://schema.org/Text)
    + Allowed values: one Of (`ok`, `defectiveLamp`, `columnIssue`, `brokenLantern`)
        + Or any other value meaningful to the application and not covered by the values above. 
    + Attribute metadata:
        + `timestamp`: Timestamp when the last update of the attribute happened.
            + Type: [DateTime](http://schema.org/DateTime)
    + Mandatory

How should we structure this `status` field **if** we also want to store this metadata `timestamp`? If we do this, shouldn't `status` attribute type be of `StructuredValue`? 

The listed example 
```json
 {
      "id": "streetlight:guadalajara:4567",
      "type": "Streetlight",
      "location": {
        "type": "Point",
        "coordinates": [  -3.164485591715449, 40.62785133667262 ]
      },
      "areaServed": "Roundabouts city entrance",
      "status": "ok",
      "refStreetlightGroup": "streetlightgroup:G345",
      "refStreetlightModel": "streetlightmodel:STEEL_Tubular_10m",
      "circuit": "C-456-A467",
      "lanternHeight": 10,
      "locationCategory" : "centralIsland",
      "powerState": "off",
      "controllingMethod": "individual",
      "dateLastLampChange": "2016-07-08T08:02:21.753Z"
    }
```

lists only the `Text` type of field, so there is no way to determine how one should store this metadata `timestamp`. 

Any help, please?

Thank you.

**Comment by jmcanterafonseca** [comment]
hi,

Sorry for the late response. Currently NGSIv2 has two different representation formats

A/ Normalized format on which every attribute is in the form:

 ```
{
   "attributeName": {
      "type": "AttributeType",
      "value": <attributeValue>
      "metadata": {
         "type": "MetadataType",
         "value": <metadataValue> 
      }
  } 
}

```

Key values format: 
{
  "attributeName": <attributeValue>
}

Internally everything is stored using the normalized format, but if the options=keyValues parameter is used then you can get a key value simplified format response, when querying data. 

All the examples in the data models are provided using the key value format, although internally they will represented using the normalized NGSIv2 representation by the corresponding NGSIv2 implementation, typically the Orion Broker. 

That means you don't need to use a structured value but just use the format below when creating a new entity

```
{
   "status": {
      "type": "Text",
      "value": "ok",
      "metadata": {
         "timestamp": "2017-10-02T12:00:09",
         "type": "DateTime"
      }
   }
}

When you query for the entity you will get the representation above or you could get the key values representation, the one you paste or the one present in the examples section, if you provide the options=keyValues modifier. 

I hope this helps

**Comment by jmcanterafonseca** [comment]
closing. please reopen if not clear @PedroMD
