### ISSUE TITLE
Do we want be stricter on flake8 (PEP8) violations on new pull requests?

### ISSUE THREAD

**Issue by cclauss** [Fiware/dataModels#147]
__OPTIONAL:__ [.travis.yml](https://github.com/Fiware/dataModels/blob/master/.travis.yml#L9-L12) currently runs flake8 in two passes.  The first pass looks for a handful of crucial errors and fails the build on these.  The second treats all remaining issues only as warnings.  The output looks like this:
* https://travis-ci.org/Fiware/dataModels/jobs/282605654#L1559

If there are any issues such as unused imports, long lines, etc. that we want future PRs to fix then we could move those issues from the second pass to the first pass and fail the build on those violations.

Some projects like CPython and Django treat all issues as unacceptable but others projects do not care about style issues.

**Comment by jmcanterafonseca** [comment]
let's keep as it is for the moment with regards to flake8. 

I would force that Travis checks that PEP8 rules are met.

**Comment by cclauss** [comment]
These two statements seem to contradict each other.  The first statement says we should not be strict on PEP8 violations and the second says that we should be more strict on PEP8 violations (the [flake8 Exxx](https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes) issues).

**Comment by jmcanterafonseca** [comment]
oh, then I'm totally in favour of forcing compliance with PEP8 rules

I'm afraid we will be failing, would you be able to provide a pull request which solves the issue over all .py files? I guess it is a matter of running autopep8, isn't it?

**Comment by jmcanterafonseca** [comment]
code landed

do we need to modify the travis.yml recipe as well?
