### ISSUE TITLE
check validity of examples against each json schema

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/dataModels#150]
it is needed to add to the travis build the check of the validity of each example.json against each JSON Schema. please check the validate.sh in order to find how to check the validity of JSON data against JSON Schemas using the ajv tool

**Comment by jmcanterafonseca** [comment]
@cclauss would you like to work on this?

**Comment by cclauss** [comment]
We would need to add the [ajv](https://github.com/epoberezkin/ajv) tool to the repo.  It is not clear to me how to do that.  Once it is added to the repo, I could work on mods to validate.sh

**Comment by chicco785** [comment]
hi, i need to review it, but i create a node-js script that uses ajv to parse all the folders to provide results. this could be called from the .travis.yml to validate pull requests.

**Comment by chicco785** [comment]
I created a pull request with the validator #160

**Comment by jmcanterafonseca** [comment]
closing as this has been fixed with the landing of the validator
