### ISSUE TITLE
provide missing JSON Schemas 

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/dataModels#151]
there are some data models which JSON Schema is missing. We need to provide it together with the example.json

@cclauss would you like to work on this?

**Comment by chicco785** [comment]
@jmcanterafonseca i have already worked out some of them... may be i can do few pull requests. but first I need to check what i did :) (was few months ago...)

**Comment by jmcanterafonseca** [comment]
@chicco785 please could you make a pull request with the data models you may have and then we can assign someone to complete them?

**Comment by jmcanterafonseca** [comment]
we currently have a nice pull request from XapiX that provides all the missing JSON Schemas. It will be landing soon ... ;)

**Comment by jmcanterafonseca** [comment]
I think we can now close this
