### ISSUE TITLE
Is correct that areaServed is an attribute of address property?

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#156]
https://github.com/Fiware/dataModels/blob/fb59108062c0e60bed2b039428e00a180bc0cea6/common-schema.json#L68

it looks duplicated inside the Location-Commons, as stand alone property and attribute of address property.  while the first case seems correct, the second one seems a mistake (but I may be wrong:))

**Comment by jmcanterafonseca** [comment]
yes it is correct, it can be both
