### ISSUE TITLE
[Parking] OffStreetParking doc examples include not documented properties

### ISSUE THREAD

**Issue by gtorodelvalle** [Fiware/dataModels#16]
In https://github.com/Fiware/dataModels/blob/master/Parking/OffStreetParking/doc/spec.md there are some examples in the lower part including properties such as `maximumParkingDuration` which are not documented, including its purpose and other details such as the type.

**Comment by jmcanterafonseca** [comment]
oh it is documented but there is a typo

maximumAParkingDuration vs maximumParkingDuration
