### ISSUE TITLE
Is there a global vs. local issue in read_geojson_data()?

### ISSUE THREAD

**Issue by cclauss** [Fiware/dataModels#167]
Does malaga_airqualityobserved_import.py work properly?  [read_geojson_data()](https://github.com/Fiware/dataModels/blob/master/Environment/AirQualityObserved/harvest/malaga_airqualityobserved_import.py#L39) seems to write data to local variables which shadow global variables.  Then other functions look for that data in the global variables.  I would have thought that these statements would be important for read_geojson_data() to work as expected:
```python
global districts_data
global neighbourhoods_data
```

Or perhaps read_geojson_data() could be modified to return these two variables.

**Comment by jmcanterafonseca** [comment]
you can propose an alternative way

**Comment by cclauss** [comment]
It works as is.
