### ISSUE TITLE
What versions of Python are supported?

### ISSUE THREAD

**Issue by cclauss** [Fiware/dataModels#169]
My assumption is all the currently supported versions of CPython: 2.7, 3.4, 3.5, and 3.6.  If so, we can safely remove the import of the with_statement which was only needed for Python 2.5 and earlier.
* https://github.com/Fiware/dataModels/search?utf8=✓&q=with_statement&type=

**Comment by jmcanterafonseca** [comment]
ok, go ahead

thanks
