### ISSUE TITLE
waste container example undefined attribute

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#190]
`dateNextActuation` is present in the example, but undefined in the spec (and json schema)

**Comment by chicco785** [comment]
correct attribute may be 'nextActuationDeadline'

**Comment by jmcanterafonseca** [comment]
@chicco785 if this is not fixed, please could you fix it?

**Comment by chicco785** [comment]
if you confirm my assumption i will

**Comment by jmcanterafonseca** [comment]
@chicco785 any update on this?

**Comment by jmcanterafonseca** [comment]
fixed
