### ISSUE TITLE
Air Quality Observed: measurand attribute is not documented 

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#195]
in the readme example there this attribute:

"measurand":
        [
            "SO2,4.0,GQ,Sulfur Dioxide",
            "CO,0.3,GP,Carbon Monoxide",
            "NO,18.0,GQ,Nitrogen Monoxide",
            "NO2,46.0,GQ,Nitrogen Dioxide",
            "NOx,73.0,GQ,Nitrogen oxides"
        ],

which is not then used in the spec neither in the .json files. I suppose it should be removed, given that contains duplicated information. But it a guess.

**Comment by jmcanterafonseca** [comment]
yes, this attribute is deprecated, and should be removed

**Comment by chicco785** [comment]
I made a PR #198. I wonder if we shouldn't review the model, there are few things that are not in aligned with the last practises. For example, values of gases are not defined. I am also not sure it is a good idea to allow to reference directly attributes from the WeatherObserved data model. The default modality should always be the reference to the entity.

**Comment by jmcanterafonseca** [comment]
values of gases, yes they are defined, but not individually, but in general. please check. 

wrt WeatherObserved, yes you might be right. a pull request could be welcome. although you might need to modify many different things, such as readme, harvest python scripts, etc. etc. it can be quite a few work ...

**Comment by chicco785** [comment]
i wondered if for completeness it wouldn't be better to list the actual values of gases as by the normative reference you link (and consequently update them in the schema).

as regards WeatherObserved, let's open it as an issue, if no one else come first, i will work on the pr when I find a slot.

**Comment by jmcanterafonseca** [comment]
you can use the GSMA IoT Big Data  Harmonised Datamodel document as reference, it is mentioned the WHO recommended parameters. You can list some of the pollutants but I would leave it open to new pollutants as per the current specification

**Comment by jmcanterafonseca** [comment]
closing as this is fixed
