### ISSUE TITLE
should we update models to json schema draft v6?

### ISSUE THREAD

**Issue by chicco785** [FIWARE/dataModels#196]
regardless, probably it would be useful to add the schema version reference in all the schemas.
```
"$schema": "http://json-schema.org/draft-04/schema#",
```

**Comment by jmcanterafonseca** [comment]
what's new in v6?

**Comment by chicco785** [comment]
http://json-schema.org/draft-06/json-schema-migration-faq.html

anyhow, i think we should be consistent, not in all schema we define the version.

**Comment by jmcanterafonseca** [comment]
everything align with latest JSON Schema. we can reopen if needed
