### ISSUE TITLE
any additional property is considered valid in the current schemas

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#197]
During the validation any example that include an attribute not describe in the json schema is valid.

This is not easy to solve, and may require heavy reworking of the schemas.
See discussion on [json-schema.org](http://json-schema.org/draft-06/json-schema-migration-faq.html#q-what-happened-to-all-the-discussions-around-re-using-schemas-with-additionalproperties).

**Comment by jmcanterafonseca** [comment]
that is on purpose,. we do not want to restrict attributes to only those described there
