### ISSUE TITLE
Device Example

### ISSUE THREAD

**Issue by juliozinga** [Fiware/dataModels#200]
In this example:
How will the user or app know the temperature range of the device: Celsus, Fahrenheit or Kelvin?
Miss some information in this example.
What do you suggest? @jmcanterafonseca @chicco785 

https://github.com/Fiware/dataModels/edit/master/Device/Device/doc/spec.md

{
  "id": "device-9845A",
  "type": "Device",
  "category": ["sensor"],
  "controlledProperty": ["fillingLevel","temperature"],
  "controlledAsset": ["wastecontainer-Osuna-100"],
  "ipAddress": "192.14.56.78",
  "mcc": "214",
  "mnc": "07",
  "batteryLevel": 0.75,
  "serialNumber": "9845A",
  "refDeviceModel": "myDevice-wastecontainer-sensor-345",
  "value": "l=0.22;t=21.2",
  "deviceState": "ok",
  "dateFirstUsed": "2014-09-11T11:00:00Z",
  "owner": ["http://person.org/leon"]
}

**Comment by jmcanterafonseca** [comment]
the model is telling that there is a device which is controlling certain properties, such as temperature and actually the device could be giving the temperature using different units, but that would be part of specific data models modelling the entities which temperature is sensed by this device

**Comment by chicco785** [comment]
to add to @jmcanterafonseca reply, you would probably use in the specific data model a metadata to define different units

**Comment by juliozinga** [comment]
In [DeviceModel](https://github.com/Fiware/dataModels/blob/352798a8bab0bb9633fce40897860388fe162fc7/Device/DeviceModel/doc/spec.md) the attribute **controlledProperty** is a candidate to add the metadata...

**Comment by jmcanterafonseca** [comment]
closed. please reopen if not fine
