### ISSUE TITLE
Code of example

### ISSUE THREAD

**Issue by juliozinga** [Fiware/dataModels#213]
in this commit: https://github.com/Fiware/dataModels/commit/352798a8bab0bb9633fce40897860388fe162fc7

See this comment:

This example, don't is accept as a orion json inner, i think.
Maybe: 
```
{
        "id": "PointOfInterest-A-1Concha-123456",
        "type": "PointOfInterest",
		"ipAddress": {
    		"type": "List",
    		"value": ["192.14.56.78"]
			}

  }
```

or:

```
{        "id": "PointOfInterest-A-1Concha-123456",
        "type": "PointOfInterest",
        "ipAddress": {
                 "type": "Text",
                 "value": "192.14.56.78"
                 }
}
```

If I get this example and test in Orion, will return: 

```
{
    "error": "BadRequest",
    "description": "attribute must be a JSON object, unless keyValues option is used"
}
```

I think this transformation is difficult for a beginner to use and understand.

**Comment by jmcanterafonseca** [comment]
you need to use the keyValue mode

**Comment by juliozinga** [comment]
This information needs to be present in an explanation close to each example.

**Comment by chicco785** [comment]
Hi Julio,
Thx for all this precious feedbacks.

I was thinking two things:
- to add a paragraph on the doc on how testing the examples with the context broker
- to introduce in the validation of model an option to test them in the context broker 

iFede - Fede's mobile edition

**Comment by chicco785** [comment]
#215 provides the automatic support check against context broker

**Comment by chicco785** [comment]
#217 add notes to all documents

**Comment by chicco785** [comment]
this issue can be closed
