### ISSUE TITLE
Error in Device Example code

### ISSUE THREAD

**Issue by juliozinga** [Fiware/dataModels#214]
I try in orion send the [exemple code](https://github.com/Fiware/dataModels/blob/master/Device/Device/example.json) of Device.
 But orion show:
```
{
    "error": "BadRequest",
    "description": "Invalid characters in attribute value"
}
```

If I remove : the line `"value": "l=0.22;t=21.2", `
Orion recevies the input.
Or later do two changes:
`"value": ["0.22","21.2"],`
Represented as `"value":{"type":"StructuredValue","value":["0.22","21.2"],"metadata":{}}`
and
`"value": "0.22,21.2",`
Represented as:  `"value":{"type":"Text","value":"0.22,21.2","metadata":{}}`

What do you think?
Are these implementations interesting?
What is the best?

**Comment by juliozinga** [comment]
Reading the specification, my suggestion is Text as Attribute Type:
`"value": "0.22;21.2"`

**Comment by chicco785** [comment]
indeed = is not a supported character: https://fiware-orion.readthedocs.io/en/master/user/forbidden_characters/index.html#forbidden-characters

@jmcanterafonseca what is the official solution in this case?

**Comment by chicco785** [comment]
the error is confirmed, check the build of the new validator (PR #215)

**Comment by chicco785** [comment]
build line where the error is identified: https://travis-ci.org/Fiware/dataModels/jobs/319934415#L561

**Comment by jmcanterafonseca** [comment]
drop the = or encode it using encodeURIComponent

2017-12-21 23:04 GMT+01:00 Federico M. Facca <notifications@github.com>:

**Comment by chicco785** [comment]
Should we land a PR for it?

iFede - Fede's mobile edition

**Comment by chicco785** [comment]
@jmcanterafonseca this issue can be closed.
