### ISSUE TITLE
device-schema.json structure problems?

### ISSUE THREAD

**Issue by 10aboskin** [FIWARE/dataModels#218]
I’m using AJV to validate data against the schema, but AJV is unable to resolve the refs in “Device-Commons” definition that reference definitions within it’s own schema. Testing on http://jsonschemalint.com/ shows that device-schema.json is a valid schema under the draft-06 specification but not the draft-04 specification.

I also noticed that the “SupportedProtocolType” definition is currently nested inside the “ControlledPropertyType” definition.

**Comment by chicco785** [comment]
you should pass the referenced schemas. for your convenience, there is a whole [testing framework] (https://github.com/Fiware/dataModels/tree/master/validator) for checking schemas and example against schemas.

see this build as example of validator run:
https://travis-ci.org/Fiware/dataModels/jobs/324521765

**Comment by 10aboskin** [comment]
in this case, the referenced schema is the schema itself. 
<img width="512" alt="screen shot 2018-01-22 at 3 50 06 pm" src="https://user-images.githubusercontent.com/7806115/35226872-dcd2a6fc-ff8c-11e7-909d-392db82152b4.png">
here the "Device-Commons" definition is trying to reference definitions from its own schema as seen here 
<img width="336" alt="screen shot 2018-01-22 at 3 58 34 pm" src="https://user-images.githubusercontent.com/7806115/35226987-219f65d6-ff8d-11e7-8674-ff52bd985790.png">

Again, this seems to be an acceptable practice in version draft-06, but not draft-04. Is this an inconsistency between this schema and other DataModel schemas?

**Comment by chicco785** [comment]
@10aboskin to be honest i didn't study the difference. what i can say that the validation is based on a version of ajv that use draft-04 schema.

**Comment by jmcanterafonseca** [comment]
all schemas are validating ok, thus closing this issue.
