### ISSUE TITLE
broked link http://json-schema.org/geojson/geometry.json

### ISSUE THREAD

**Issue by juliozinga** [Fiware/dataModels#220]
This link fail http://json-schema.org/geojson/geometry.json
in: https://github.com/Fiware/dataModels/blob/master/PointOfInteraction/SmartPointOfInteraction/schema.json;
and https://fiware.github.io/dataModels/common-schema.json#/definitions/Location-Commons.

**Comment by chicco785** [comment]
it's not a broken link, simply (and unfortunately) the schema is not referenciable. correct @jmcanterafonseca ?

**Comment by jmcanterafonseca** [comment]
correct. I think we can close this.
