### ISSUE TITLE
Minor glitches in the description of the location and address attributes of the BikeHireDockingStation spec

### ISSUE THREAD

**Issue by aarranz** [Fiware/dataModels#223]
Currently, the [spec document](https://github.com/Fiware/dataModels/blob/079dca98e6122cc9105bc4a7b36c315cf0d763da/Transportation/Bike/BikeHireDockingStation/doc/spec.md) describes the `address` attribute as to be "Mandatory if `location` is not defined". This description is strange because the `location` attribute is described to be mandatory, so it will be clearer to mark the `address` attribute directly as optional.

Another option would be to mark the `location` attribute "Mandatory if `address` is not defined." as we do on other specs.

**Comment by jmcanterafonseca** [comment]
@aarranz I would prefer to mark location as "Mandatory if address is not present"

**Comment by jmcanterafonseca** [comment]
@aarranz please could you submit a PR fixing this?

**Comment by aarranz** [comment]
The PR was merged, so I think this issue can be closed
