### ISSUE TITLE
Add support for a third attribute for identifying vehicles

### ISSUE THREAD

**Issue by aarranz** [Fiware/dataModels#231]
Current Spec for `Vehicle` requires to provide at least one of the following attributes: `vehiclePlateIdentifier` or `vehicleIdentificationNumber `. When providing open data using this data model, this usually is a problem, because is not usual to provide that information. Some public services provide the `vehiclePlateIdentifier` like most of the car/motor sharing services, but others don't provide any of both. In any case, they usually provide an extra id (local to the fleet).

So I propose to add a new attribute (e.g. `fleetId`) and require a value for one those attributes.

**Comment by jmcanterafonseca** [comment]
fleetVehicleId could work. Please could make a PR addressing this?
