### ISSUE TITLE
Discrepancies between WeatherObserved spec and example harversters

### ISSUE THREAD

**Issue by aarranz** [Fiware/dataModels#234]
The `WeatherObserved` spec (and schema) documents the use of the `barometricPressure` attribute while the example harvesters (e.g. [`spain_weather_boserved_harvester.py`](https://github.com/Fiware/dataModels/blob/master/Weather/WeatherObserved/harvest/spain_weather_observed_harvest.py)) uses an `atmosphericPressure` attribute. So, there are two options:

- Leaving untouched the spec, so we have to fix the harvesters to use a `barometricPressure` attribute  instead of the `atmosphericPressure` one.
- Or renaming the `barometricPressure` attribute in the spec and schema to `atmosphericPressure`.

I can provide a PR once decided what option fits better.

**Comment by jmcanterafonseca** [comment]
@aarranz the authoritative source is https://www.gsma.com/iot/wp-content/uploads/2016/06/CLP.26-v4.0.pdf ,

please could you make a PR so that there is alignment?

**Comment by jmcanterafonseca** [comment]
@aarranz ping

**Comment by aarranz** [comment]
Sorry for not answering. Yes, I will provide a PR.

**Comment by jmcanterafonseca** [comment]
closing. this was fixed
