### ISSUE TITLE
Could not obtain token

### ISSUE THREAD

**Issue by abemuis95** [Fiware/dataModels#235]
I tried to obtain the auth token to get the data on AirQualityObserved but failed. Can anyone help me?

Environment:
CLI : Command Prompt
OS: Windows 10
Python : ver 2.7
![curl error](https://user-images.githubusercontent.com/12205191/38774866-3d95e244-40a4-11e8-8b0d-eabcf2c1fcb3.PNG)
![token json](https://user-images.githubusercontent.com/12205191/38774872-5ecbe3be-40a4-11e8-9fb1-3b18db3b7494.png)

**Comment by chicco785** [comment]
hi,
i think the issue has nothing to do with the air quality model, but with
auth service. so this project is not the best one where to ask for help.

**Comment by jmcanterafonseca** [comment]
Currently we are not maintaining that infrastructure and will be down for a couple of months until we upgrade it to a new one.

**Comment by caa06d9c** [comment]
Hi! 

Please, check URL, Username and Password:
As an example (AirQuality):

Request token and export it as Env variable:
`export TOKEN=$(curl -s https://iotbd.lab.fiware.org/ngsi/token -d '{"username": "fiware.user1@gmail.com", "password": "C4@%N6oF3RqX"}')`

Request AirQuality data from Madrid:
`curl -s --header 'fiware-service:airquality' --header 'fiware-servicepath:/Madrid' --header "x-auth-token:$TOKEN" "https://iotbd-pep.lab.fiware.org/v2/entities?type=AirQualityObserved" | python -mjson.tool`

You can also define specific station and date:
`curl -s --header "fiware-service:airquality" --header "fiware-servicepath:/Madrid" --header "x-auth-token:$TOKEN" "https://iotbd-pep.lab.fiware.org/v2/entities?type=AirQualityObserved&attrs=measurand,address&q=dateObserved>2018-10-29;stationCode:'28079004'&orderBy=dateObserved&options=keyValues" | python -mjson.tool`

Example of output:
`[
    {
        "address": {
            "addressCountry": "ES",
            "addressLocality": "Madrid",
            "streetAddress": "Plaza de Espa\u00f1a"
        },
        "id": "Madrid-AirQualityObserved-28079004-2018-10-29T02:00:00",
        "measurand": [
            "CO,0.2,GP,Carbon Monoxide",
            "NO,2.0,GQ,Nitrogen Monoxide",
            "NO2,13.0,GQ,Nitrogen Dioxide",
            "NOx,16.0,GQ,Nitrogen oxides"
        ],
        "type": "AirQualityObserved"
    },
...`
