### ISSUE TITLE
[TrafficFlowObserved]

### ISSUE THREAD

**Issue by chicco785** [FIWARE/dataModels#238]
while the specs refer to `occupancy` the example mentions `capacity`.
are they the same? what's the correct one in case?

**Comment by jmcanterafonseca** [comment]
I've made a PR with a tiny fix. but I realised that no JSON Schema is available nor example.json.

**Comment by jmcanterafonseca** [comment]
I've assigned Fede as he intended to work on providing the JSON Schema

**Comment by jmcanterafonseca** [comment]
@chicco785 do you think you would be able to provide a JSON Schema?

**Comment by chicco785** [comment]
on the stack for next week (hopefully)

**Comment by jmcanterafonseca** [comment]
already fixed, closing
