### ISSUE TITLE
bullet point issues with readthedocs

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/dataModels#259]
In the Urban Mobility data models readthedocs generated documentation we are facing the issue of bad indented bullet points. Issue is with the markdown. 

See 
http://fiware-datamodels.readthedocs.io/en/latest/UrbanMobility/Agency/doc/spec/index.html

as an example (same issue with the rest of data models)

**Comment by caa06d9c** [comment]
fix in #260
