### ISSUE TITLE
Add fire as new category/subcategory in the Alert data model

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/dataModels#264]
In the Alert data model, currently we have "forestFire" as a subcategory of "weather" , and the semantics is "there is a risk of forestFire" due to the current weather conditions, for instance high temperature. 

But we also need something to convey that there is currently a fire, so may be that could be done using the "security" category, or even could be used using another category named "fire" and subcategory "forestFire", "buildingFire" etc. 

What do you think? @chicco785 @jason-fox

**Comment by jason-fox** [comment]
I would see a separate `fire` category as being too specific IMHO - how many different types of fire would you need? 

Personally I see the `security` category being sufficient  for  encapsulating *Things you want to run away from fast*.   

Maybe use the following within `security` category
* `suspiciousAction`
* `robbery`
* `assault`
* `civilDisorder` . (e.g. Riot, Protest March)
* `buildingFire`
* `forestFire` ... etc.

The weather category shouldn't really contain `forestFire` - it should contain `fireRisk`

**Comment by jmcanterafonseca** [comment]
+1. 
@jason-fox would you be able to make a PR with these changes? it is not urgent, just something for your backlog ...

**Comment by jason-fox** [comment]
Whilst we are at it - why is `tsunami` a Weather event? -  it is not caused by the weather

Surely  `tsunami` and ``earthquake` (missing) should be `environmental`?

**Comment by jmcanterafonseca** [comment]
@chicco785 designed it but now on vacation, so we should ask him

**Comment by chicco785** [comment]
i wouldn't use "environmental", for me this is something related to "monitoring" and somehow related to human activities effect.

"natural" ? 

regarding "fire" i agree with @jason-fox , and in general I think we should provide guidelines, but not being too specific - at least unless we have the usecase to proper test and validate the categorization.

**Comment by jason-fox** [comment]
A modest Proposal :

* `traffic` :
(trafficJam, carAccident, carWrongDirection, carStopped,  pothole, roadClosed, roadWorks, hazardOnRoad, injuredBiker) 

* `naturalDisaster` :  :heavy_exclamation_mark: 
(flood, tsunami, coastalEvent, earthquake) 

> `tsunami` and `coastalEvent` moved from Weather

* `weather` :
(rainfall, highTemperature, lowTemperature, heatWave, coldWave, ice,  snow, wind, fog, tornado, tropicalCyclone,  hurricane, snow/ice, thunderstorms, fireRisk,  avalanches, floodRisk)

> `forestFire` is now `fireRisk`, `rain/flood` is now `floodRisk`


* `environment` :
(airPollution, waterPollution, pollenConcentration)

* `health` :
(asthmaAttack, bumpedPatient, fallenPatient, heartAttack )

* `security` category
( suspiciousAction, robbery, assault, civilDisorder, buildingFire, forestFire)

>  Fire examples added.

**Comment by jmcanterafonseca** [comment]
@jason-fox please could you nail it down by making a PR?

Thanks!

**Comment by jmcanterafonseca** [comment]
closed as fixed.
