### ISSUE TITLE
[WeatherObserved] visibility is ambiguous

### ISSUE THREAD

**Issue by TK009** [FIWARE/dataModels#282]
Property `visibility` is documented as
```
Allowed values: One of (veryPoor, poor, moderate, good, veryGood, excellent)
```
But this is very ambiguous, no sensor outputs this kind of scale. This is a problem for me because my data source gives me visibility as length in meters that can be seen. I didn't find easily any tables that could categorize visibility in the required scale.

**Comment by chicco785** [comment]
hi @TK009 
the data model is derived from [GSMA](https://www.gsma.com/iot/wp-content/uploads/2018/07/CLP.26-v5.0.pdf) work that indeed states:

> visibility | Number or QuantitativeValue | Defines the observed visibility nominally in metres or in an alternative measurement according to specified unitCode if QuantitativeValue is used

so we should surely need to tackle also the the numeric support, but preserving backward compatibility with string values.

I believe that this values have been inherited from existing API, i.e. https://opendata.aemet.es

**Comment by chicco785** [comment]
@jmcanterafonseca what do you think?

**Comment by TK009** [comment]
Thanks for helping.
It's hard to browse documentation with google translate. If someone can find how this visibility scale is calculated from meters, I think it would be useful to add into the data models documentation for both data producers and consumers. Other way would be to add an attribute metadata to link to a specification like in airQualityIndex of AirQualityObserved.

**Comment by jmcanterafonseca** [comment]
I would suggest we stick to what it is said by GSMA spec. To keep backwards compatibility we would need to allow a string, though. 

@chicco785 could you provide a PR to fix this? otherwise, I can take it.

**Comment by caa06d9c** [comment]
Do we need to change them both (examples and harvesters)? visibility is present only in common weather schema.
