### ISSUE TITLE
Particulate matter values in AirQualityObserved?

### ISSUE THREAD

**Issue by aapris** [Fiware/dataModels#292]
We've several different sensors which measure particulate matter in the air and we get PM10 and PM2.5 values out from them. However, I've no clue how to publish the data e.g. in Fiware NGSI V2 broker since https://github.com/Fiware/dataModels/blob/master/specs/Environment/AirQualityObserved/doc/spec.md doesn't mention particulate matter or PM at all.

Can I just add (leagally) `"pm2.5"` and `"pm10"` values to the same level with `"relativeHumidity"` and `"temperature"` and others? Or is it possible at all to publish these values under the topic AirQualityObserved?

**Comment by jmcanterafonseca** [comment]
They should be PM10 and PM2.5 and yes at the same level .
