### ISSUE TITLE
[Weather observed] order of longitude and latitude are not specified.

### ISSUE THREAD

**Issue by ilarimikkonen** [Fiware/dataModels#299]
AFAIK, there is no standard for this, so would be better to specify "lng" and "lat" in "coordinates"

**Comment by chicco785** [comment]
@ilarimikkonen 
I am not sure to which notation you refer to, but if you check the GeoJSON spec, this is clear:
https://tools.ietf.org/html/rfc7946#section-3.1.1

**Comment by ilarimikkonen** [comment]
great! can you mention that somewhere in the documentation?

**Comment by chicco785** [comment]
@ilarimikkonen thanks for raising the point.

@jmcanterafonseca @jason-fox probably we need an "intro" spec, providing few details on the "common" models. Feelings?

**Comment by jmcanterafonseca** [comment]
I don't believe we need to duplicate in a specification something which it is already said in another specification which is referenced as normative. So -1.

**Comment by chicco785** [comment]
i think explaining few things for the "general models" and pointing to the spec is a plus, that could make adopters life easier. of course (which we have to do anyway) this implies that in case of relevant changes to the reference, we would need to make updates.

in the end, this is about lowering barriers for adoption :)

**Comment by jmcanterafonseca** [comment]
well if you want to create a tutorial on how to use the Data Models, fine, but I don't want to maintain in the specifications things which are not essential

**Comment by chicco785** [comment]
Indeed it could be a short guide on how to use the models. We have now a documentation on how to build them, but not something for the users.

I will open a different ticket.
