### ISSUE TITLE
Officialize in the doc the version of JSON Schema we comply with

### ISSUE THREAD

**Issue by chicco785** [FIWARE/dataModels#300]
This may help also to clarify #218 . This may have impact also on the validator and fixes to the schemas.

**Comment by jmcanterafonseca** [comment]
@chicco785 can you propose something? What is the latest version of JSON Schema supported by ajv and other tools? 

that should give us a lower boundary of what versions to adhere to.

**Comment by chicco785** [comment]
currently we do validation with a version of ajv that supports draft-04 (despite not defined in all schemas), but the last version of ajv supports up to draft-07.

an approach could be:
1. point to schema draft-04 in all schemas (not all JSON schemas have the reference to it currently)
1. officialise that the current version supported is draft-04
1. test new ajv with configuration to support draft-04, migrate to the new version
1. introduce an additional validation to check if the schema is compliant with draft-07
1. report a warning if the schema is not compliant with draft-07
1. officialise that schema version will be migrated to draft-07
1. slowly migrate all schemas to draft-07

feelings?

**Comment by jmcanterafonseca** [comment]
all schemas are now compliant with Draft 07. Idea will be to be aligned with latest version of JSON Schema. closing for now. Reopen if needed
