### ISSUE TITLE
Fix dead links

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#315]
Within  .textlintrc, I think you may want to add 

 "no-dead-link": {
       "ignoreRedirects": true,
       "ignore": [
          "mailto:*",
          " https://schema.org"
       ]
    }

**Comment by jmcanterafonseca** [comment]
/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/guidelines.md
  204:39  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/datamodel_template.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/datamodel_template.md')                                            no-dead-link
  205:46  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/doc/spec.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/doc/spec.md')    no-dead-link
  207:44  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/README.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/README.md')        no-dead-link
  209:46  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/schema.json is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/schema.json')    no-dead-link
  211:47  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/example.json is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/specs/Weather/WeatherObserved/example.json')  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/howto.md
  57:9  error  "the" is repeated  write-good

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Environment/AirQualityObserved/doc/spec.md
  100:47  error  "the" is repeated  write-good

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Environment/AirQualityObserved/README.md
  8:24  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Environment/PointOfInterest/AirQualityStation is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Environment/PointOfInterest/AirQualityStation')  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Parking/OffStreetParking/doc/spec.md
  74:27  error  http://www.datex2.eu/sites/www.datex2.eu/files/DATEXIISchema_2_2_2_1.zip is dead. (301 Moved Permanently)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Parking/OnStreetParking/doc/spec.md
  105:31  error  http://www.datex2.eu/sites/www.datex2.eu/files/DATEXIISchema_2_2_2_1.zip is dead. (301 Moved Permanently)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Parking/ParkingGroup/doc/spec.md
  50:31  error  http://www.datex2.eu/sites/www.datex2.eu/files/DATEXIISchema_2_2_2_1.zip is dead. (301 Moved Permanently)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Parking/ParkingSpot/doc/spec.md
  82:50  error  "the" is repeated  write-good

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/PointOfInterest/AirQualityStation/README.md
  10:33  error  http://datos.madrid.gob is dead. (request to http://datos.madrid.gob failed, reason: getaddrinfo ENOTFOUND datos.madrid.gob datos.madrid.gob:80)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/PointOfInterest/Beach/doc/spec.md
  8:13  error  http://www.tourspain.es/en-us/paginas/index.aspx is dead. (request to https://www.tourspain.es/en-us/paginas/index.aspx failed, reason: unable to verify the first certificate)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/PointOfInterest/Museum/doc/spec.md
  8:13  error  http://www.tourspain.es/en-us/paginas/index.aspx is dead. (request to https://www.tourspain.es/en-us/paginas/index.aspx failed, reason: unable to verify the first certificate)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/StreetLighting/StreetlightGroup/doc/spec.md
  40:40  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/StreetLighting/StreetlightCabinetController/doc/spec.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/StreetLighting/StreetlightCabinetController/doc/spec.md')  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Transportation/EVChargingStation/doc/spec.md
  12:8  error  https://fiware.github.io/dataModels/specs/Transportation/ChargingStation/schema.json is dead. (404 Not Found)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Transportation/Road/doc/spec.md
  58:58  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Transportation/Road/doc/OpenStreetMap is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Transportation/Road/doc/OpenStreetMap')  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Transportation/RoadSegment/doc/spec.md
  104:31  error  http://www.datex2.eu/sites/www.datex2.eu/files/DATEXIISchema_2_2_2_1.zip is dead. (301 Moved Permanently)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Transportation/Vehicle/Vehicle/doc/spec.md
   54:19  error  https://github.com/telefonicaid/iotagent-node-lib/blob/develop/README.md#TimeInstant is dead. (404 Not Found)  no-dead-link
   74:19  error  https://github.com/telefonicaid/iotagent-node-lib/blob/develop/README.md#TimeInstant is dead. (404 Not Found)  no-dead-link
   86:19  error  https://github.com/telefonicaid/iotagent-node-lib/blob/develop/README.md#TimeInstant is dead. (404 Not Found)  no-dead-link
   96:27  error  https://github.com/telefonicaid/iotagent-node-lib/blob/develop/README.md#TimeInstant is dead. (404 Not Found)  no-dead-link
  151:27  error  https://github.com/telefonicaid/iotagent-node-lib/blob/develop/README.md#TimeInstant is dead. (404 Not Found)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/Activity/doc/spec.md
  21:8  error  https://fiware.github.io/dataModels/specs/User/UserActivity/schema.json is dead. (404 Not Found)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/UserContext/doc/spec.md
  50:24  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/Device/Device/doc/spec.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/Device/Device/doc/spec.md')                        no-dead-link
  53:18  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/Device/Device/doc/spec.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/Device/Device/doc/spec.md')                        no-dead-link
  57:30  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/UserContext/UserActivity/doc/spec.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/UserContext/UserActivity/doc/spec.md')  no-dead-link
  59:24  error  /Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/UserContext/UserActivity/doc/spec.md is dead. (ENOENT: no such file or directory, access '/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/User/UserContext/UserActivity/doc/spec.md')  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Weather/WeatherForecast/README.md
  50:2  error  http://www.aemet.es/xml/municipios/localidad_46250.xml" is dead. (404 Not Found)  no-dead-link

/Users/jasonfox/Workspace/jason-fox/catalogue-forks/dataModels/specs/Weather/WeatherObserved/doc/spec.md
  65:12  error  https://github.com/Fiware/dataModels/blob/master/Weather/WeatherForecast/spain_weather_forecast_harvest.py#L135 is dead. (404 Not Found)  no-dead-link

✖ 31 problems (31 errors, 0 warnings)





The textrc file should read:


{
  "rules": {
    "terminology": true,
    "common-misspellings": true,
    "write-good": {
      "adverb": false,
      "passive": false,
      "tooWordy": false,
      "weasel": false
    },
    "no-dead-link": {
       "ignoreRedirects": true,
        "ignore": [
          "mailto:*",
          "https://schema.org/*",
          "http://schema.org/*"
       ]
    }
  }
}

**Comment by jmcanterafonseca** [comment]
I think we can close. @caa06d9c please check

**Comment by caa06d9c** [comment]
fixed. but build still with errors because of lint check.
