### ISSUE TITLE
Markdown in vehicle model seems broken

### ISSUE THREAD

**Issue by chicco785** [Fiware/dataModels#326]
check Location and other attributes: the bullets are not correctly displayed:
* https://github.com/Fiware/dataModels/blob/master/specs/Transportation/Vehicle/Vehicle/doc/spec.md
* https://fiware-datamodels.readthedocs.io/en/latest/Transportation/Vehicle/Vehicle/doc/spec/index.html

**Comment by jmcanterafonseca** [comment]
fixed
