### ISSUE TITLE
Weather-schema - "null" values in several attribute types

### ISSUE THREAD

**Issue by emastrosimone** [FIWARE/dataModels#335]
In the [weather-schema.json](https://github.com/Fiware/dataModels/blob/master/specs/Weather/weather-schema.json) what is the meaning of having "null" values in several attribute types , as the following?
```
.... "temperature": {
               "type": [
                  "number",
                  "null"
               ]
            } .......
```

Is there a particular reason or is it an error?

**Comment by jmcanterafonseca** [comment]
it was thought at that time that using null could be a good idea, to convey the fact that something was not known. Given the fact that NGSI-LD does not allow null values, I think we should remove that.

Would you be happy to make a PR fixing that? @emastrosimone

**Comment by jmcanterafonseca** [comment]
fixed now. no longer null allowed
