### ISSUE TITLE
Point of Interest schema should have anyOf for address and location.

### ISSUE THREAD

**Issue by emastrosimone** [Fiware/dataModels#372]
As stated by the [spec.md](https://github.com/Fiware/dataModels/blob/master/specs/PointOfInterest/PointOfInterest/doc/spec.md)
>For Location: Mandatory if address is not defined. and vice versa.

So I think the schema.json should have:
```
"anyOf": [{"required": ["location"]}, {"required": ["address"]}],
```
instead of `location` field in the required part. In that way any entity having the address only would fail.

**Comment by jmcanterafonseca** [comment]
good point. please could you provide a patch?

thanks

**Comment by jmcanterafonseca** [comment]
fixed!
