### ISSUE TITLE
[TrafficFlowObserved] - add vehicle type to model

### ISSUE THREAD

**Issue by neeeel** [FIWARE/dataModels#384]
the trafficFlowObserved model is almost suitable for storing classified counts, but doesnt allow you to specify what sort of vehicle was observed. I will have a number devices that classifies traffic flow, and each device can produce a number of counts based on vehicle type, eg pedestrian, car, lorry, etc. It doesnt really make sense to create a new model that is almost exactly the same .

Would it be possible to alter the model so that under "intensity" you could have multiple key:value pairs

eg{"intensity":[
    {"vehicleType":"Car",
      "value":12
      }.
      {"vehicleType":"Lorry",
      "value":17
      }
    ]
}

**Comment by jmcanterafonseca** [comment]
@neeeel thanks for reporting this.

We have two possible approaches, the one you are suggesting, which has the drawback of backwards compatibility and a slightly more complicated format to be consumed by clients, and also a slightly less clean representation from the NGSI point of view

or

Can we just have an extra attribute on TrafficFlowObserved which indicates what is the type of Vehicle referred by the measurement? We already have a definition of vehicle types so it would be easy ... 

https://github.com/FIWARE/dataModels/blob/master/specs/Transportation/Vehicle/Vehicle/doc/spec.md

Drawback of this approach is that we can potentially have multiple entities for each measured area ...

**Comment by neeeel** [comment]
Hi, thanks for your reply
I have been in touch with some synchronicity people who have suggested that for TrafficFlowObserved, I can set the "ControlledProperty" to "TrafficFlow" and then have the "value" field as a "codified string 

eg "value":"car:1;van:12"

so its not exactly json and the consumer will still need to some work to format the data at their end. Do you think that would be acceptable and would adhere to the FIWARE data model spec?

**Comment by jmcanterafonseca** [comment]
in that case you would be using the Device data model and not the TrafficFlowObserved data model. I would not recommend that solution though. I would go for a solution as the ones I mentioned.

**Comment by neeeel** [comment]
How would this change impact you? ( i am assuming you are the maintener of this model?)

Ideally I would like the first solution ( a json dictionary of key-value pairs) but I realise you need to think about things like backwards compatibility

**Comment by jmcanterafonseca** [comment]
@neeeel I propose to just add an extra attribute with the Vehicle Type defaulting to `car`

WDYT?

**Comment by neeeel** [comment]
Im not sure that would do, as I can have multiple values per observation, each one with a different vehicle type and count, 

Can you give me an example?

**Comment by jmcanterafonseca** [comment]
it is easy. You can have as many TrafficFlowObserved entities as types of vehicles you are observing. So it is a matter of having a `vehicleType` attribute in the TrafficFlowObserved entity.

**Comment by neeeel** [comment]
our VehicleFlowObserved entities would be being updated every 15 minutes, but that should be fine? 

If so, I am happy to add in a vehicleType attribute

**Comment by jmcanterafonseca** [comment]
yes I don't see any problem in that.

**Comment by jmcanterafonseca** [comment]
@neeeel  would you be willing to make a contribution to fix it? it shouldn't be difficult

**Comment by neeeel** [comment]
Hi, yes, I will give it a go in the next week.
thanks for your help

**Comment by neeeel** [comment]
Hey, I made a pull request a few days ago, would be good if you could check it out and let me know if I did it right

**Comment by jmcanterafonseca** [comment]
closed
