### ISSUE TITLE
problems running the validator: Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by ilarimikkonen** [FIWARE/dataModels#387]
HI,

ilari@ilari-XPS13-9333:~/dataModels/validator$ sudo npm install -g
/usr/local/bin/validate -> /usr/local/lib/node_modules/fiware-model-validator/validate.js
npm WARN lifecycle deasync@0.1.13~install: cannot run in wd deasync@0.1.13 node ./build.js (wd=/home/ilari/dataModels/validator/node_modules/deasync)
+ fiware-model-validator@0.5.1
added 123 packages from 106 contributors in 1.715s
ilari@ilari-XPS13-9333:~/dataModels/validator$ validate
/home/ilari/dataModels/validator/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/ilari/dataModels/validator/node_modules/deasync/build/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/build/Debug/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/build/Release/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/out/Debug/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/Debug/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/out/Release/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/Release/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/build/default/deasync.node
 → /home/ilari/dataModels/validator/node_modules/deasync/compiled/11.9.0/linux/x64/deasync.node
    at bindings (/home/ilari/dataModels/validator/node_modules/bindings/bindings.js:88:9)
    at /home/ilari/dataModels/validator/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/home/ilari/dataModels/validator/node_modules/deasync/index.js:76:2)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)

is it me or some problem with validator?

**Comment by jmcanterafonseca** [comment]
probably you need to invoke the validator with parameters, see for instance our Travis recipe

https://github.com/FIWARE/dataModels/blob/master/.travis.yml#L37

**Comment by chicco785** [comment]
issue is at installation time, and given that ci tests works, it looks something related to @ilarimikkonen  node environment.

**Comment by jmcanterafonseca** [comment]
is this fixed? can we close @ilarimikkonen ?

**Comment by ilarimikkonen** [comment]
yes, problem with my node setup. closing
