### ISSUE TITLE
GtfsFrequency - StartTime and  EndTime regex is wrong

### ISSUE THREAD

**Issue by emastrosimone** [FIWARE/dataModels#396]
The regex 
```
 ^([0][0-9]|1[0-9]|4[0-7]):[0-5][0-9]:[0-5][0-9]$
```
in `startTime` and `endTime` doesn't match strings like: `20:00:00`

A good Regex could be:
```
^([0-3][0-9]|4[0-7]):[0-5][0-9]:[0-5][0-9]
```
matching times larger than 24:00:00 (as expected by the [GTFS Specification](https://developers.google.com/transit/gtfs/reference/#frequenciestxt)).

At the same time this avoids frequencies larger than 48 hours.

**Comment by jmcanterafonseca** [comment]
@emastrosimone an easy fix, could you provide a contribution?

**Comment by jmcanterafonseca** [comment]
fixed
