### ISSUE TITLE
[Agri Data Models] When possible reference AgroVoc

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#408]
When feasible, in Agri Data Models it would be great to add a reference to the corresponding AgroVoc concept, that could be done using a property of type URI 

http://aims.fao.org/vest-registry/vocabularies/agrovoc

Example:

```
{
  "id": "urn:ngsi-ld:AgriCrop:xxx",
  "type": "AgriCrop",
  "name": "Tomato",
  "alternateName": "Solanum lycopersicum"
  "agriVocConcept": {
    "type": "Property",
    "value": "http://aims.fao.org/aos/agrovoc/c_4475"
  }
}
```

**Comment by fdelavega** [comment]
I think this is finished

**Comment by jmcanterafonseca** [comment]
fixed
