### ISSUE TITLE
[Agri models] add owner to the Entities for which it could make sense

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#409]

**Comment by jmcanterafonseca** [comment]
an owner should be a pointer to an entity of type https://schema.org/Person or https://schema.org/Organization

**Comment by jmcanterafonseca** [comment]
name of the attribute: `ownedBy`

**Comment by jmcanterafonseca** [comment]
name of the attribute: `ownedBy`

**Comment by fdelavega** [comment]
AgriParcelOperation and AgriParcelRecord both point to an AgriParcel which includes the owner. On the other hand, crop, pest, and product type represent generic concepts, so I don't think an ownedBy field should be included there.
 
@jmcanterafonseca do you think ownerBy property should be included in any other datamodel?

**Comment by jmcanterafonseca** [comment]
we can close, thanks!
