### ISSUE TITLE
[Agri] Enhance Device to include implements in Agri

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#425]
https://github.com/ADAPT/ADAPT/blob/c38badbeb9049a817353b3d810845adf3e6ff0b1/source/ADAPT/Equipment/DeviceElementTypeEnum.cs

**Comment by fdelavega** [comment]
Not sure all the categories included in the linked enum can be considered a device. Fo example, machine used for tractors would map with Vehicle data model

**Comment by jmcanterafonseca** [comment]
done.
