### ISSUE TITLE
reorder attributtes spec.md of `OffStreetParking` `OnStreetParking` to harmonize

### ISSUE THREAD

**Issue by stbnrivas** [FIWARE/dataModels#447]
Hello, would you accept a pull request with the reorder attributtes of spec.md into both files to get that both have the same order of attributtes. Differents attributtes will be place at the end.

However this be useful to see easilier differents between and whether we need two models or can be simplifyed to only one

I promise be careful ;-). If you prefer I can do step by step into multiples PR.

**Comment by jmcanterafonseca** [comment]
@stbnrivas  two PRs would be ok, thanks!

**Comment by stbnrivas** [comment]
facepalm ... I'm sorry, I did not remember splitting into two PR. Do you prefer the divided approach? I can do it if you want

**Comment by jmcanterafonseca** [comment]
fixed
