### ISSUE TITLE
LD @context automatic generation improvements

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#448]
1/ 
When invoking (for the automatic @context generation) `https://github.com/FIWARE/dataModels/blob/master/tools/ldcontext_generator.py` the URI prefix shall be `https://uri.fiware.org/ns/dataModels` , instead of `http://uri.fiware.org/ns/dataModels`, 
i.e change `http` by `https`

2/
We need an HTTP redirection from `https://schema.lab.fiware.org/ld/context/` to `https://schema.lab.fiware.org/ld/jsonldcontext.jsonld`

**Comment by caa06d9c** [comment]
I can redirect everything from https://schema.lab.fiware.org/ld to https://schema.lab.fiware.org/ld/jsonldcontext.jsonld, is it ok?

**Comment by caa06d9c** [comment]
Done. 
URLs to check:

- [Full](https://schema.lab.fiware.org/ld/jsonldcontext.jsonld)
- [Folder](https://schema.lab.fiware.org/ld/)
- [SubFolder](https://schema.lab.fiware.org/ld/context/)
- [Wrong FIle](https://schema.lab.fiware.org/ld/test.json)

**Comment by jmcanterafonseca** [comment]
@caa06d9c wrong file should give 404 response. we only want /ld/ and /ld/context/ to work, can we just adjust the RegExp to fix it and to be more restrictive?

**Comment by caa06d9c** [comment]
> @caa06d9c wrong file should give 404 response. we only want /ld/ and /ld/context/ to work, can we just adjust the RegExp to fix it and to be more restrictive?

Done

**Comment by jmcanterafonseca** [comment]
@caa06d9c as per the feedback I got from W3C better not to use the trailing '/' so we just need to

redirect from `https://schema.lab.fiware.org/ld/context` to `https://schema.lab.fiware.org/ld/jsonldcontext.jsonld``

sorry for the mess

thanks!

**Comment by caa06d9c** [comment]
Done. `/ld`,` /context`   redirects to `/ld/jsonldcontext.jsonld`

**Comment by jmcanterafonseca** [comment]
verified. closed
