### ISSUE TITLE
[Civic Issue Tracking] Datamodel names/types should not have colon mark

### ISSUE THREAD

**Issue by jaimeventura** [FIWARE/dataModels#462]
Datamodel name ‘Open311:ServiceType’ and ‘Open311:ServiceRequest’ should not have colon mark, so that in doesn’t interfere with the id convention ’ urn:ngsi-ld:<datamodel_name>:<identifier>’.

**Comment by jmcanterafonseca** [comment]
@jaimeventura very true!. please could you propose a fix? 

thanks!

**Comment by jaimeventura** [comment]
@jmcanterafonseca: I just noticed that the folder where these datamodels are "Open311_ServiceRequest" and "Open311_ServiceType". They should be named "Open311ServiceRequest" and "Open311ServiceType" respectively (without the '_'), right?

**Comment by jmcanterafonseca** [comment]
@jaimeventura yep, please could you take care? also you would need to update `mkdocs.yml`

thanks!
