### ISSUE TITLE
[GtfsStop] 'operatedBy' property should not be Mandatory

### ISSUE THREAD

**Issue by jaimeventura** [FIWARE/dataModels#463]
Although the existence is understandable, it shouldn't be mandatory since doest exist in Stops original documentation[1].

Im available to create a PR for this, but first I would like raise attention to the following.

GTFSSTOP datamodel documentation[2] states that 'operatedBy' attribute's type is Relationship and 'It shall point to an Entity of Type GtfsAgency'( Agency that operates this stop.)

The documentation about Stops[1] states: 'Multiple routes may use the same stop.'
And, the documentation for the route[3] say, regarding agency_id :'This field is required when the dataset provides data for routes from more than one agency in agency.txt.'
So, several routes may be provided by several agencies.
Which, in my opinion, implies that a 'Stop' may be used by multiple 'agencies'.
(Considere that multiple agencies may provide several routes which cross or overlap and share stops).

And so, 'operatedBy' attribute, if specified, should be an array of relations maybe.

[1] https://developers.google.com/transit/gtfs/reference/#stopstxt
[2] https://fiware-datamodels.readthedocs.io/en/latest/UrbanMobility/GtfsStop/doc/spec/index.html
[3] https://developers.google.com/transit/gtfs/reference/#routestxt

**Comment by jmcanterafonseca** [comment]
@jaimeventura it makes sense. looking forward to your PR.

**Comment by jmcanterafonseca** [comment]
@jaimeventura can we close this?

**Comment by jaimeventura** [comment]
I believe so.
Thank you.
