### ISSUE TITLE
in harvesters use URIs (urn:ngsi-ld:<Type>:xxxx) as Entity ids

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#482]
so that we can promote the usage of URNs as Entity Ids

**Comment by caa06d9c** [comment]
May be ngsi? Or schema must be LD as well?

**Comment by jmcanterafonseca** [comment]
at this stage we keep the v2 schema and just change ids to be URNs, ok?

later we can add an option to harvesters to generate LD content as well,
but that's another story
