### ISSUE TITLE
https://schema.lab.fiware.org/ld/context to wrap the Core `@context`

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/dataModels#490]
We need that `https://schema.lab.fiware.org/ld/context` returns 

```
Content-Type: application/ld+json
{
   "@context": [
     "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
     "https://schema.lab.fiware.org/ld/fiware-datamodels-context.jsonld"
   ]
}
```
and `https://schema.lab.fiware.org/ld/fiware-datamodels-context.jsonld` should return what is currently returned by `https://schema.lab.fiware.org/ld/context` (`application/ld+json`)

**Comment by caa06d9c** [comment]
Done. Please, check the result.

**Comment by jmcanterafonseca** [comment]
@caa06d9c works perfectly, thanks!
