### ISSUE TITLE
advice required on updating NoiseLevelObserved datamodel

### ISSUE THREAD

**Issue by mrypma** [FIWARE/dataModels#491]
I'd like to extend the NoiseLevelObserved datamodel to include the frequency spectrum. Which means that it needs to include additional entities that have a frequency and a value. To make it generic, I'd prefer not to be restricted to predefined frequencies and not create attributes like freq_100Hz, freq_150hz etc since the frequency used can pretty much be any positive integer. Please advice on the correct way to implement such attributes in an efficient general way.

**Comment by jmcanterafonseca** [comment]
type: "StructuredValue": {
  "value": { 
        "frequencies": {
           "100": 
           "150"
  }
}

**Comment by jmcanterafonseca** [comment]
closing as this already landed
